fashionhouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('house.urls')),
     path('vendor/',include('vendor.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

house/urls.py
from django.urls import path
from .views import  homeView, storeView, aboutView, contactFormView

app_name = 'house'


urlpatterns = [
    path('fashionhouse/home/', homeView, name = 'homeView'),
    path('fashionhouse/store/', storeView, name = 'storeView'),
    path('fashionhouse/about/', aboutView, name = 'aboutView'),
    path('fashionhouse/contact/', contactFormView, name = 'contactFormView'),
]

house/models.py
from django.db import models
from vendor.models import Vendor
# Create your models here.

class Post(models.Model):
    vendor = models.ForeignKey( Vendor , on_delete= models.CASCADE, null = True, blank = True)
    name =  models.TextField(max_length = 1500)
    description = models.TextField(max_length = 1500)
    date_posted = models.DateTimeField( auto_now_add=True)
    likes = models.IntegerField(default = 0)
    photo = models.ImageField( upload_to='post-image', null = True, blank = True)

    def __str__(self):
        return f'{self.name} by {self.vendor.user.username}'


class Comment(models.Model):
    post = models.ForeignKey( Post , on_delete=models.CASCADE)
    text = models.TextField(max_length = 1500)


class Testimonial(models.Model):
    # user = models.OneToOneField( User,  on_delete=models.CASCADE)
    text = models.TextField(max_length = 1500)
    date_posted = models.DateTimeField( auto_now_add=True)





house/forms.py
from django import forms


class contactForm(forms.Form):
    name = forms.CharField(widget = forms.TextInput(attrs = {'class': 'form-control', 'type':"text", 'name':"name", 'placeholder':"Name"}),  max_length=1500, required=True)
    email = forms.EmailField(widget = forms.TextInput(attrs = {'class': 'form-control', 'type':"email", 'name':"email", 'placeholder':"Email"}),  max_length=1500, required=True)
    message = forms.CharField(widget = forms.Textarea(attrs = {'class': 'form-control', 'type':"text", 'name':"message", 'placeholder':"Message", 'rows':"14"}), max_length=2000, required=True)

house/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import contactForm
from .models import Post
# Create your views here.


def homeView(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
    }
    return render (request, 'house/home_page.html', context)


def storeView(request):
    return render (request, 'house/stores_page.html')


def aboutView(request):
    return render (request, 'house/about_page.html')


def contactFormView(request):
    if request.method == "POST":
        form = contactForm(request.POST)
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(name, email, message)
    else:
        form = contactForm()
    context = {
        'form': form
    }
    return render (request, 'house/contact_form_page.html', context)

house/templates/house/about_page.html
{% extends 'house/base.html' %}
{% load static %}


{% block style %}  
<link rel="stylesheet" href="{% static 'css/about.css' %}"> 
{% endblock style %}
    

{% block title %} Store{% endblock title %}
    
{% block header %}
 {% include 'house/webparts/navbar.html' %} 
{% endblock header %}


{% block main %} 
<div class="jumbotron jumbotron-fluid ">
    <div class="container">
        <h1 class="display-3 top">Fashion House</h1>
        <p class="lead">About us</p>
        <hr class="my-2">
        <p class="explain">
           <span style="color: crimson; font-weight: 700; font-size: 40px;">F</span>ashion House is
            a place for fashion designers to showcase their designs , it is a place for people
            to find the right fashion designers to design their clothes for them , so maybe
            you are a work from home fashion designer who has a machine but doesn't have a shop , 
            Fashion house is your shop,it is a place where
           fashion designers/tailors are connected to people who are intrested in finding the right fashion designer
           for their products, it is also a place where investors meet good fashion designers to partner with them,
           hire them or run contracts with them.
           Fashion house is a place where we do everything about designing clothes , we are so intrested in the 
           run way that we help fashion designers showcase their talents, design, skills and potentials so
           people who are looking for a fashion designer can get the best of them. <br><br>
            In fashion House , people who are looking for a good fashion designer would connect with the tailors and
           fashion designers here to make and deliver their clothes to them at home without any stress
           it is a place where your design meets the market.
           Fashion House is a free website for everyone to post their designs and attract potential clients.
        </p>
    </div>
</div>
 {% endblock main %}
    
  






house/templates/house/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@300&family=Work+Sans&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@200&family=Noto+Sans+JP:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@300&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Caveat&display=swap" rel="stylesheet">        
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   
   {% block style %} {% endblock style %}
    <title>FashionHouse | {% block title %}{% endblock title %} </title> 
   
  </head>
  <body>

  {% block header %}{% endblock header %}

<main>
 {% block main %} {% endblock main %} 
</main>

{% include 'house/webparts/footer.html' %}

{% include 'house/webparts/scripts.html' %}
  
</body>
</html>

house/templates/house/contact_form_page.html
{% extends 'house/base.html' %}
{% load static %}


{% block style %}  
<link rel="stylesheet" href="{% static 'css/contact.css' %}"> 
{% endblock style %}
    

{% block title %} Store{% endblock title %}
    
{% block header %}
 {% include 'house/webparts/navbar.html' %} 
{% endblock header %}


{% block main %} 
<div class="contact-clean">
  <!--social media links-->
<div class="social-icons">
<a href="#"><i class="fab fa-facebook"></i></a>
<a href="#"><i class="fab fa-twitter"></i></a>
<a href="#"><i class="fab fa-whatsapp"></i></a>
<a href="#"><i class="fab fa-instagram"></i></a>
</div>
  <form method="POST" action="">
   {% csrf_token %}
      <h2 class="text-center">Contact us</h2>
      <div class="form-group"> {{form.name}}</div>
      <div class="form-group">{{form.email}}</div>
      <div class="form-group">{{form.message}}</div>
      <div class="form-group"><button class="btn btn-default" type="submit">Send </button></div>
  </form>
</div>
 {% endblock main %}
    
  






house/templates/house/home_page.html
{% extends 'house/base.html' %}
{% load static %}


{% block style %}  <link rel="stylesheet" href="{% static 'css/style.css' %}"> {% endblock style %}
    

{% block title %} Home{% endblock title %}
    
{% block header %}
<header>
  <header>
    <nav class="navbar navbar-light navbar-expand-md">
      <div class="container-fluid"><a class="navbar-brand text-light" href="#">Fashion House</a>
        <!--the toggler for the full screen navigation menu-->
          <span><img src="{% static 'images/item.png' %}" class="menu" onclick="openNav()"> </span>
        
          <div class="collapse navbar-collapse" id="navcol-1">
              <ul class="nav navbar-nav mr-auto">
                  <li role="presentation" class="nav-item"><a class="nav-link active text-light " href="{% url 'house:homeView' %}">Home</a></li>
                  <li role="presentation" class="nav-item"><a class="nav-link text-light" href="{% url 'house:storeView' %}">Store</a></li>
                  <li role="presentation" class="nav-item"><a class="nav-link text-light" href="{% url 'house:aboutView' %}">About</a></li>
                  <li role="presentation" class="nav-item"><a class="nav-link text-light" href="{% url 'house:contactFormView' %}">Contact</a></li>
                  <li role="presentation" class="nav-item"><a class="nav-link text-light" href="login.html">Login</a></li>
                  <li role="presentation" class="nav-item"><a class="nav-link text-light" href="register.html">Register</a></li>
              </ul>
          </div>
      </div>

      <!--navigation menu for mobile devices-->
      {% include 'house/webparts/mobile_navbar.html' %}
  </nav>
  <!--page intro-->
  <div class="intro">
    <h2>LET THE WORLD SEE YOUR DESIGN</h2>
    <p>Local tailors post their designs here to attract customers online</p>
    <a href="about.html">
  <button type="button" class="btn btn-default learn">Learn more</button>
  </a>
  </div>
  </header>
 
</header> 
{% endblock header %}


{% block main %} 
<h3 class="text-center mt-4 mb-4">Trends</h3>
<!--THE NEW TESTING OF IMAGE GRID FOR MAKING IMAGES LOOK GREAT-->
<div class="row grid">
  <div class="column">
    
    {% for posts in posts  %}
    <div class="image-container">
      <a href="#"><img src="{{posts.photo.url}}" class="img-fluid"></a>
      <p> by {{posts.vendor.user.username}}</p>
    </div>
    {% endfor %}
      
<!--   
  <div class="image-container">
    <a href="#"><img src="../static/images/man.jpg" class="img-fluid"></a>
    <p> by Emma Davies</p>
  </div>
  <div class="image-container">
    <a href="#"><img src="../static/images/alex.jpg" class="img-fluid"></a>
    <p> by alexander's</p>
  </div>    
  <div class="image-container">
    <a href="#"><img src="../static/images/manly.jpg" class="img-fluid"></a>
    <p> by Peter wears</p>
  </div>  
  <div class="image-container">
    <a href="#"><img src="../static/images/big.jpg" class="img-fluid"></a>
    <p> by big boys</p>
  </div>
  </div>
  <div class="column">
    <div class="image-container">
      <a href="#"><img src="../static/images/sisters.jpg" class="img-fluid"></a>
      <p> by Tolu styles</p>
    </div>
    <div class="image-container">
      <a href="#"><img src="../static/images/piano.jpg" class="img-fluid"></a>
      <p> by The Keys</p>
    </div>
    <div class="image-container">
      <a href="#"><img src="../static/images/show.jpg" class="img-fluid"></a>
      <p> by Jane snow</p>
    </div>
    <div class="image-container">
      <a href="#"><img src="../static/images/murat.jpg" class="img-fluid"></a>
      <p> by Murat Ekanem</p>
    </div>
    <div class="image-container">
      <a href="#"><img src="../static/images/fold.jpg" class="img-fluid"></a>
      <p> by Mk collections</p>
    </div>
    <div class="image-container">
      <a href="#"><img src="../static/images/ank1.webp" class="img-fluid"></a>
      <p> by Anike's</p>
    </div>
    </div>
  <div class="column">
    <div class="image-container">
      <a href="#"><img src="../static/images/real.jpg" class="img-fluid"></a>
      <p> by Tunde casual</p>
    </div>
    <div class="image-container">
      <a href="#"><img src="../static/images/tall.jpg" class="img-fluid"></a>
      <p> by Tall Tayo</p>
    </div>
    <div class="image-container">
      <a href="#"><img src="../static/images/leon.jpg" class="img-fluid"></a>
      <p> by Leon p</p>
    </div>
    <div class="image-container">
      <a href="#"><img src="../static/images/jenny.jpg" class="img-fluid"></a>
      <p> by Jenny & doll</p>
    </div>
    </div>
  <div class="column">
    <div class="image-container">
      <a href="#"><img src="../static/images/sweet.jpg" class="img-fluid"></a>
      <p> by Clothations</p>
    </div>
    <div class="image-container">
      <a href="#"><img src="../static/images/asoebi.png" class="img-fluid"></a>
      <p> by Wearing Me</p>
    </div>
    <div class="image-container">
      <a href="#"><img src="../static/images/vasile.jpg" class="img-fluid"></a>
      <p> by Yisa tailor</p>
    </div>
    <div class="image-container">
      <a href="#"><img src="../static/images/prince.jpg" class="img-fluid"></a>
      <p> by Prince Mohammed</p>
    </div>-->
    </div>
</div>  
<!--go to store button
<div class="text-center mt-5">
  <a href="stores.html"><button type="button" class="btn btn-default see-more-button"> See More</button></a>
</div>



<!--END OF TEST, YOU CAN NOW DELETE IF NOT NEEDED-->
  <div class="highlight-wing pt-4">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="intro">
                    <h2 style="color: crimson;" class="pt-5">Are You A Fashion Designer ?</h2>
                    <p style="color: black">Post your designs on fashion House for free, get customers
                      to patronise you <br>
                  send your design to Our whatsapp group along with your name and phone number <br>
                and let customers see your design </p>
                    <a class="btn btn-default learn text-center" role="button" href="contact.html">Send Now</a>
                  </div>
            </div>
            <div class="col-sm-4">
                <div class="d-none d-sm-block wing"><img class="device img-fluid" src="{% static 'images/wings.png' %}" />
                    <div class="screen"></div>
                </div>
            </div>
        </div>
    </div>
</div>
 <!--testimonial section-->
 <div class="testimonials-clean">
  <div class="container">
      <div class="intro">
          <h2 class="text-center text-dark">Testimonials </h2>
          <p class="text-center">Our customers and tailors love us! Read what they have to say below</p>
      </div>
      <div class="row people">
          <div class="col-md-6 col-lg-4 item">
              <div class="box">
                  <p class="description">I am a fan of this website, i come here whenever i want to look
                    for a good fashion designer</p>
              </div>
              <div class="author"><img class="rounded-circle" src="../static/images/test1.jpg" />
                  <h5 class="name">Mary Johnson</h5>
                  <p class="title">CEO of greene's Inc</p>
              </div>
          </div>
          <div class="col-md-6 col-lg-4 item">
              <div class="box">
                  <p class="description">I have been a tailor and since i started posting my designs
                    here, customers have been contacting me all the time
                  </p>
              </div>
              <div class="author"><img class="rounded-circle" src="../static/images/test2.jpg" />
                  <h5 class="name">kemi Davids</h5>
                  <p class="title">Founder of Kemi styles.</p>
              </div>
          </div>
          <div class="col-md-6 col-lg-4 item">
              <div class="box">
                  <p class="description">I have been looking for money to get a shop for some time now, 
                    but since i started posting my clothes here, i haven't been able to meet up to all the customers demands
                  </p>
              </div>
              <div class="author"><img class="rounded-circle" src="../static/images/test1.jpg" />
                  <h5 class="name">Emily Clark</h5>
                  <p class="title">Owner of Creative Ltd.</p>
              </div>
          </div>
      </div>
  </div>
</div>
 {% endblock main %}
    
  

house/templates/house/stores_page.html
{% extends 'house/base.html' %}
{% load static %}


{% block style %}  
<link rel="stylesheet" href="{% static 'css/stores.css' %}"> 
{% endblock style %}
    

{% block title %} Store{% endblock title %}
    
{% block header %}
 {% include 'house/webparts/navbar.html' %} 
{% endblock header %}


{% block main %} 
<br>
  <div class="row ">
    <div class="col-md-10 offset-md-1">
        <div class="card m-auto" style="max-width:850px">
            <div class="card-body">
                <form class="d-flex align-items-center"><i class="fas fa-search d-none d-sm-block h4 text-body m-0"></i>
                  <input class="form-control form-control-lg flex-shrink-1 form-control-borderless" type="search" placeholder="Search designers or keywords" name="searchbar" />
                  <button class="btn btn-primary btn-lg search-btn" type="submit">Search</button></form>
            </div>
        </div>
    </div>
  </div>
  
  <!--NEW GRID IMAGE LAYOUT-->
  <!-- <div class="row grid">
    <div class="column">
      <div class="image-container">
      <a href="#"><img src="../static/images/woman.jpg" class="img-fluid"></a>
      <p> by Mariam Abiodun</p>
    </div>
    <div class="image-container">
      <a href="#"><img src="../static/images/man.jpg" class="img-fluid"></a>
      <p> by Emma Davies</p>
    </div>
    <div class="image-container">
      <a href="#"><img src="../static/images/alex.jpg" class="img-fluid"></a>
      <p> by alexander's</p>
    </div>    
    <div class="image-container">
      <a href="#"><img src="../static/images/manly.jpg" class="img-fluid"></a>
      <p> by Peter wears</p>
    </div>  
    <div class="image-container">
      <a href="#"><img src="../static/images/big.jpg" class="img-fluid"></a>
      <p> by big boys</p>
    </div>
    </div>
  
    <div class="column">
      <div class="image-container">
        <a href="#"><img src="../static/images/sisters.jpg" class="img-fluid"></a>
        <p> by Tolu styles</p>
      </div>
      <div class="image-container">
        <a href="#"><img src="../static/images/piano.jpg" class="img-fluid"></a>
        <p> by The Keys</p>
      </div>
      <div class="image-container">
        <a href="#"><img src="../static/images/show.jpg" class="img-fluid"></a>
        <p> by Jane snow</p>
      </div>
      <div class="image-container">
        <a href="#"><img src="../static/images/murat.jpg" class="img-fluid"></a>
        <p> by Murat Ekanem</p>
      </div>
      <div class="image-container">
        <a href="#"><img src="../static/images/fold.jpg" class="img-fluid"></a>
        <p> by Mk collections</p>
      </div>
      <div class="image-container">
        <a href="#"><img src="../static/images/ank1.webp" class="img-fluid"></a>
        <p> by Anike's</p>
      </div>
      </div>
  
    <div class="column">
      <div class="image-container">
        <a href="#"><img src="../static/images/real.jpg" class="img-fluid"></a>
        <p> by Tunde casual</p>
      </div>
      <div class="image-container">
        <a href="#"><img src="../static/images/tall.jpg" class="img-fluid"></a>
        <p> by Tall Tayo</p>
      </div>
      <div class="image-container">
        <a href="#"><img src="../static/images/leon.jpg" class="img-fluid"></a>
        <p> by Leon p</p>
      </div>
      <div class="image-container">
        <a href="#"><img src="../static/images/jenny.jpg" class="img-fluid"></a>
        <p> by Jenny & doll</p>
      </div>
      </div>
  
    <div class="column">
      <div class="image-container">
        <a href="#"><img src="../static/images/sweet.jpg" class="img-fluid"></a>
        <p> by Clothations</p>
      </div>
      <div class="image-container">
        <a href="#"><img src="../static/images/asoebi.png" class="img-fluid"></a>
        <p> by Wearing Me</p>
      </div>
      <div class="image-container">
        <a href="#"><img src="../static/images/vasile.jpg" class="img-fluid"></a>
        <p> by Yisa tailor</p>
      </div>
      <div class="image-container">
        <a href="#"><img src="../static/images/prince.jpg" class="img-fluid"></a>
        <p> by Prince Mohammed</p>
      </div>
      </div>
  </div> -->
  <!--the pagination-->
  <nav aria-label="...">
    <ul class="pagination justify-content-center mt-5">
      <li class="page-item">
        <a class="page-link text-dark" href="#">Previous</a>
      </li>
      <li class="page-item  active"><a class="page-link text-dark" href="#">1</a></li>
      <li class="page-item"><a class="page-link text-dark" href="#"> 2</a></li>
      <li class="page-item"><a class="page-link text-dark" href="#">3</a></li>
      <li class="page-item">
        <a class="page-link text-dark" href="#">Next</a>
      </li>
    </ul>
  </nav>
 {% endblock main %}
    
  




